<a href="https://colab.research.google.com/github/BartekPodgorski/Python/blob/main/data-science-training/01_intro/Linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Vector norm in R2


In [ ]:
v1 = np.array([0,4])
np.linalg.norm(v1)

4.0

Euclidesian norm in Rn


In [3]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Distance between points

In [4]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [5]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

Matrix multiplication

In [7]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])

In [8]:
Z = np.dot(X,Y)

In [9]:
Z

array([[ 2],
       [-6]])

In [10]:
Z.shape

(2, 1)

In [11]:
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])

In [12]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Determinant

In [14]:
A = np.array([[2,4],[-1,3]])
np.linalg.det(A)

9.999999999999998

Trace of the matrix

In [15]:
A = np.array([[2,4],[-1,3]])
np.trace(A)

5

Identity matrix

In [16]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Inverse matrix


In [17]:
B = np.linalg.inv(A)
B


array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [19]:
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

Transpose matrix

In [20]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Solving systems of equations

In [21]:
A = np.array([[2,4],[1,-1]])

In [22]:
B =np.array([[10],[-1]])

In [23]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [24]:
X

array([[1.],
       [2.]])